import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3000';
const cached = 'C:/Users/mychu/AppData/Local/ms-playwright/chromium-1217/chrome-win64/chrome.exe';
const browser = await chromium.launch({ headless:true, ...(existsSync(cached) ? { executablePath:cached } : {}), args:['--enable-unsafe-swiftshader'] });
await mkdir('artifacts', {recursive:true});
const report = { checks: [], consoleErrors: [], accessibility: [], metrics: {} };
try {
 const context = await browser.newContext({viewport:{width:1440,height:1000}, deviceScaleFactor:1});
 const page = await context.newPage();
 page.on('pageerror', e => report.consoleErrors.push(e.message));
 await page.goto(base, {waitUntil:'networkidle'});
 await page.waitForSelector('.gallery-slide.is-current img');
 assert.equal(await page.locator('.gallery-slide').count(),6);
 await page.waitForFunction(()=>document.querySelector('.gallery-count')?.textContent.includes('02'));
 await page.getByRole('button',{name:'หยุดสไลด์',exact:true}).click();
 const stoppedCount=await page.locator('.gallery-count').innerText();
 await page.waitForTimeout(6500);
 assert.equal(await page.locator('.gallery-count').innerText(),stoppedCount);
 for(let i=1;i<=6;i++){
   await page.getByLabel('เลือกภาพสไลด์',{exact:true}).selectOption(String(i-1));
   await page.waitForTimeout(1500);
   assert.match(await page.locator('.gallery-count').innerText(),new RegExp(`0${i} /`));
   assert.equal(await page.locator('.gallery-slide.is-current img').evaluate(el=>el.complete&&el.naturalWidth>0),true);
 }
 await page.getByLabel('เลือกภาพสไลด์',{exact:true}).selectOption('0');
 await page.waitForTimeout(1500);
 report.checks.push('Six selected photos, autoplay advance, pause and all manual transitions');
 await page.screenshot({path:'artifacts/desktop-hero.png'});
 assert.equal(await page.locator('h1').count(),1);
 assert.equal(await page.locator('.project-card').count(),4);
 await page.getByRole('button',{name:'บางชัน',exact:true}).click();
 assert.equal(await page.locator('.project-card').count(),1);
 assert.match(await page.locator('.project-card').innerText(),/The Celine/);
 await page.getByLabel('งบประมาณ',{exact:true}).selectOption('over2');
 assert.equal(await page.locator('.project-card').count(),0);
 await page.getByRole('button',{name:'ดูทุกโครงการ',exact:true}).click();
 assert.equal(await page.locator('.project-card').count(),4);
 await page.getByLabel('เปิดขายแล้ว',{exact:true}).check();
 assert.equal(await page.locator('.project-card').count(),3);
 await page.getByLabel('เปิดขายแล้ว',{exact:true}).uncheck();
 report.checks.push('Project location, price, availability, empty state and reset');
 await page.getByRole('tab',{name:'02 เชื่อมต่อ'}).click();
 assert.equal(await page.locator('#living-tab-1').getAttribute('aria-selected'),'true');
 await page.locator('#living-tab-1').press('ArrowRight');
 assert.equal(await page.locator('#living-tab-2').getAttribute('aria-selected'),'true');
 report.checks.push('Lifestyle tabs: pointer and keyboard');
 await page.locator('#finance').scrollIntoViewIfNeeded();
 const original = await page.locator('.finance-result strong').innerText();
 await page.getByLabel('ระยะเวลากู้',{exact:true}).selectOption('20');
 assert.notEqual(await page.locator('.finance-result strong').innerText(),original);
 await page.getByRole('button',{name:'ประเมินกำลังซื้อ',exact:true}).click();
 assert.match(await page.locator('.finance-result').innerText(),/วงเงินกู้ประมาณ/);
 report.checks.push('Finance modes and amortization controls');
 await page.locator('.faq-list summary').first().click();
 assert.equal(await page.locator('.faq-list details').first().getAttribute('open'),'');
 report.checks.push('FAQ expansion');
 await page.getByRole('button',{name:'เปิดเมนู',exact:true}).click();
 assert.equal(await page.locator('#main-menu').evaluate(el=>el.open),true);
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#main-menu').evaluate(el=>el.open),false);
 report.checks.push('Modal navigation and Escape dismissal');
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
 await page.waitForSelector('.gallery-frame');
 await page.waitForTimeout(700);
 await page.screenshot({path:'artifacts/desktop-architecture.png'});
 const frameWidth=await page.locator('.gallery-frame').evaluate(el=>el.getBoundingClientRect().width);
 await page.evaluate(()=>scrollTo({top:document.querySelector('.gallery-hero').offsetHeight-innerHeight*1.15,behavior:'instant'}));
 await page.waitForTimeout(1800);
 assert.ok(await page.locator('.gallery-frame').evaluate(el=>el.getBoundingClientRect().width)<frameWidth*.9);
 assert.equal(await page.locator('.gallery-hero').getAttribute('data-paused'),'true');
 await page.screenshot({path:'artifacts/desktop-scroll.png'});
 const transform1=await page.locator('.project-image img').first().evaluate(el=>getComputedStyle(el).transform);
 await page.locator('#projects').scrollIntoViewIfNeeded();await page.waitForTimeout(500);
 const transform2=await page.locator('.project-image img').first().evaluate(el=>getComputedStyle(el).transform);
 assert.notEqual(transform1,transform2);
 assert.ok(await page.locator('.journey-thread path').last().getAttribute('d'));
 report.checks.push('Scroll shrinks gallery frame, pauses slides, project parallax and connected section path');
 for (let y=0;y<await page.evaluate(()=>document.body.scrollHeight);y+=750){await page.evaluate(v=>scrollTo({top:v,behavior:'instant'}),y);await page.waitForTimeout(100);}
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
 await page.waitForTimeout(1100);
 await page.screenshot({path:'artifacts/desktop-full.png',fullPage:true});
 const desktopAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 report.accessibility.push({viewport:'desktop',violations:desktopAxe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))}))});
 report.metrics.desktop = await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth,images:[...document.images].filter(i=>!i.complete || i.naturalWidth===0).map(i=>i.src),resources:performance.getEntriesByType('resource').reduce((s,r)=>s+r.transferSize,0)}));
 assert.equal(report.metrics.desktop.scrollWidth,1440);
 assert.equal(report.metrics.desktop.images.length,0);
 for(const path of ['/elysium59','/theceline','/projects/elysium-ram-interchange','/projects/wela-ramkhamhaeng']) {
   const res=await context.request.get(`${base}${path}`,{maxRedirects:0});
   assert.equal(res.status(),307); assert.equal(res.headers().location,`https://website-delta-blush-73.vercel.app${path}`);
 }
 report.checks.push('All four project slug redirects preserve the original destinations');
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 const mp=await mobile.newPage();
 await mp.goto(base,{waitUntil:'networkidle'});
 await mp.screenshot({path:'artifacts/mobile-hero.png'});
 for(let y=0;y<await mp.evaluate(()=>document.body.scrollHeight);y+=650){await mp.evaluate(v=>scrollTo({top:v,behavior:'instant'}),y);await mp.waitForTimeout(90);}
 await mp.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await mp.waitForTimeout(1000);
 await mp.screenshot({path:'artifacts/mobile-full.png',fullPage:true});
 assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth),390);
 await mp.getByLabel('เลือกภาพสไลด์',{exact:true}).selectOption('2');
 assert.match(await mp.locator('.gallery-count').innerText(),/03/);
 await mp.getByRole('button',{name:'เปิดเมนู',exact:true}).click();
 await mp.locator('#main-menu a[href="#projects"]').click();
 assert.equal(await mp.locator('#main-menu').evaluate(el=>el.open),false);
 const mobileAxe=await new AxeBuilder({page:mp}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 report.accessibility.push({viewport:'mobile',violations:mobileAxe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))}))});
 report.checks.push('390px mobile: no overflow, gallery selection, menu navigation');
 const reduced=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});
 const rp=await reduced.newPage();await rp.goto(base,{waitUntil:'networkidle'});
 assert.equal(await rp.locator('.gallery-hero').getAttribute('data-paused'),'true');
 const reducedSlide=await rp.locator('.gallery-count').innerText();
 await rp.waitForTimeout(6500);
 assert.equal(await rp.locator('.gallery-count').innerText(),reducedSlide);
 assert.equal(await rp.locator('.will-reveal').count(),0);
 report.checks.push('Reduced-motion preference disables animation and autoplay');
 const nojs=await browser.newContext({viewport:{width:1280,height:900},javaScriptEnabled:false});
 const np=await nojs.newPage();await np.goto(base,{waitUntil:'networkidle'});
 assert.equal(await np.locator('.project-card').count(),4);
 assert.equal(await np.locator('#intro-title').isVisible(),true);
 report.checks.push('No JavaScript: content and project links remain server rendered');
 const missing=await context.request.get(`${base}/unknown-page`);assert.equal(missing.status(),404);
 report.checks.push('404 handling');
 assert.equal(report.consoleErrors.length,0);
 await writeFile('artifacts/qa-report.json',JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
 assert.equal(report.accessibility.reduce((n,a)=>n+a.violations.length,0),0,'Accessibility issues found; see artifacts/qa-report.json');
} finally { await writeFile('artifacts/qa-report.json',JSON.stringify(report,null,2)); await browser.close(); }
