import { nearbyCategories, type ProjectSections } from '@/lib/projectSections';
export default function ProjectSectionsEditor({ value, onChange }: { value: ProjectSections; onChange: (value: ProjectSections) => void }) {
  const patch = (next: Partial<ProjectSections>) => onChange({...value,...next});
  const input = 'w-full rounded border border-slate-200 p-2 text-sm';
  return <div className="col-span-2 space-y-6 border-t pt-6">
    <h3 className="font-semibold">สถานที่ใกล้เคียง</h3>
    <label className="block text-sm">หัวข้อ<input className={input} value={value.nearbyTitle} onChange={e=>patch({nearbyTitle:e.target.value})} placeholder="ใกล้ทุกจังหวะของชีวิต"/></label>
    <label className="block text-sm">คำอธิบายทำเล<textarea className={input} value={value.nearbyDescription} onChange={e=>patch({nearbyDescription:e.target.value})}/></label>
    {nearbyCategories.map(category=><fieldset key={category.id} className="space-y-2 rounded border p-3"><legend className="px-2 text-sm font-medium">{category.label}</legend>{value.places.map((place,index)=>place.category===category.id && <div key={index} className="flex flex-wrap gap-2"><input aria-label="ชื่อสถานที่" placeholder="ชื่อสถานที่" className={`${input} flex-1 min-w-40`} value={place.name} onChange={e=>patch({places:value.places.map((p,i)=>i===index?{...p,name:e.target.value}:p)})}/><input aria-label="ระยะทาง" placeholder="เช่น 300 ม. หรือ 2 กม." className="w-36 rounded border p-2 text-sm" value={place.distance} onChange={e=>patch({places:value.places.map((p,i)=>i===index?{...p,distance:e.target.value}:p)})}/><button type="button" className="text-sm text-red-600" onClick={()=>patch({places:value.places.filter((_,i)=>i!==index)})}>ลบ</button></div>)}<button type="button" className="text-sm text-blue-700" onClick={()=>patch({places:[...value.places,{category:category.id,name:'',distance:''}]})}>+ เพิ่มสถานที่</button></fieldset>)}
    <h3 className="border-t pt-6 font-semibold">ความคืบหน้าโครงการ</h3>
    <label className="flex gap-2 text-sm"><input type="checkbox" checked={value.progressEnabled} onChange={e=>patch({progressEnabled:e.target.checked})}/>แสดงความคืบหน้าบนหน้าโครงการ</label>
    <div className="grid grid-cols-2 gap-3"><label className="text-sm">เดือนที่อัปเดต<input type="month" required={value.progressEnabled} className={input} value={value.progressDate} onChange={e=>patch({progressDate:e.target.value})}/></label><label className="text-sm">ภาพรวม (%)<input type="number" min="0" max="100" step="0.01" className={input} value={value.progressOverall} onChange={e=>patch({progressOverall:Number(e.target.value)})}/></label></div>
    {value.progressItems.map((item,index)=><div key={index} className="flex gap-2"><input aria-label="หมวดงาน" placeholder="เช่น งานโครงสร้าง" className={input} value={item.name} onChange={e=>patch({progressItems:value.progressItems.map((p,i)=>i===index?{...p,name:e.target.value}:p)})}/><input aria-label="เปอร์เซ็นต์งาน" type="number" min="0" max="100" step="0.01" className="w-24 rounded border p-2" value={item.percent} onChange={e=>patch({progressItems:value.progressItems.map((p,i)=>i===index?{...p,percent:Number(e.target.value)}:p)})}/><button type="button" className="text-sm text-red-600" onClick={()=>patch({progressItems:value.progressItems.filter((_,i)=>i!==index)})}>ลบ</button></div>)}
    <button type="button" className="text-sm text-blue-700" onClick={()=>patch({progressItems:[...value.progressItems,{name:'',percent:0}]})}>+ เพิ่มหมวดงาน</button>
    <label className="block text-sm">วิดีโอความคืบหน้า (YouTube)<input type="url" className={input} value={value.progressVideo} onChange={e=>patch({progressVideo:e.target.value})} placeholder="https://www.youtube.com/watch?v=..."/></label>
    <p className="text-xs text-slate-500">ใช้ข้อมูลและระยะทางที่ตรวจสอบแล้ว หมวดที่ไม่มีรายการจะไม่แสดง เปอร์เซ็นต์ภาพรวมกรอกแยกจากงานย่อย</p>
  </div>;
}
